server:
  port: 6060

spring:
  cache:
    type: redis
    # 定义cache名称，用于在缓存注解中引用，多个名称可以使用逗号分隔
    cache-names: myrediscache
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    password:
    # 连接超时时间（毫秒）
    timeout: 100
    # ClientType
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10

